# Generated by Django 5.2.6 on 2025-10-28 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(verbose_name="Fecha de Reserva")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Inicio")),
                (
                    "hora_salida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Salida"
                    ),
                ),
                (
                    "tarifa_hora",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tarifa por Hora"
                    ),
                ),
                (
                    "total_pago",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total a Pagar"
                    ),
                ),
                (
                    "codigo_qr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Código QR",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reservations.estadoreserva",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-fecha", "-hora_inicio"],
            },
        ),
    ]
