# Generated by Django 5.2.6 on 2025-10-28 20:05

from django.db import migrations

ESTADOS = [
    "Confirmada",
    "En proceso",
    "Finalizada",
    "Expirada",
    "Cancelada",
]


def poblar_estados(apps, schema_editor):
    """
    Inserta los estados de reserva iniciales en la base de datos
    """
    EstadoReserva = apps.get_model("reservations", "EstadoReserva")
    for estado in ESTADOS:
        EstadoReserva.objects.create(nombre=estado)


def reversa_poblar_estados(apps, schema_editor):
    """
    Elimina los estados de reserva insertados por la migración
    """
    EstadoReserva = apps.get_model("reservations", "EstadoReserva")
    EstadoReserva.objects.filter(nombre__in=ESTADOS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(poblar_estados, reverse_code=reversa_poblar_estados),
    ]
